title = "Squash"  # From Git
gitRepoUrl = "https://github.com/Data-Oriented-House/Squash" # From Git

gitSourceBranch = "main"
changelog = false

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Bandwidth Optimized"
description = "Carefully optimizes compression for every type so that they are represented in the most spatially efficient way. Enables sending data over the network or saving it to a datastore cheaper."
image = "/bandwidth2.png"

[[home.features]]
title = "Serialization-Deserialization"
description = "Push and pop data from buffers for quick and composible SerDes!"
image = "/Squash.png"

[[home.features]]
title = "Fully Comprehensive"
description = "Can serialize and deserialize all serializable Luau and Roblox types, even the obscure ones."
image = "/comprehensive2.png"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "Data-Oriented-House"
projectName = "Squash"
url = "https://data-oriented-house.github.io"
baseUrl = "/Squash/"
tagline = "Roblox's Comprehensive SerDes Library"

[[classOrder]]
classes = ["Squash"]

[[classOrder]]
section = "Luau"
collapsed = true
classes = [
	"string",
	# "number",
	# "uint",
	# "int",
# 	"vlq",
# 	"boolean",
# 	"buffer",
# 	"tuple",
# 	"array",
# 	"map",
# 	"record",
# 	"angle",
]

# [[classOrder]]
# section = "Roblox"
# collapsed = true
# classes = [
# 	"Axes",
# 	"BrickColor",
# 	"CatalogueSearchParams",
# 	"CFrame",
# 	"Color3",
# 	"ColorSequence",
# 	"ColorSequenceKeypoint",
# 	"DateTime",
# 	"EnumItem",
# 	"Faces",
# 	"FloatCurveKey",
# 	"Font",
# 	"NumberRange",
# 	"NumberSequence",
# 	"NumberSequenceKeypoint",
# 	"OverlapParams",
# 	"PathWaypoint",
# 	"PhysicalProperties",
# 	"Ray",
# 	"RaycastParams",
# 	"RaycastResult",
# 	"Rect",
# 	"Region3",
# 	"Region3int16",
# 	"RotationCurveKey",
# 	"TweenInfo",
# 	"UDim",
# 	"UDim2",
# 	"Vector2",
# 	"Vector2int16",
# 	"Vector3",
# 	"Vector3int16"
# ]

[navbar]
# hideableSidebar = true

[[navbar.items]]
href = "https://discord.com/channels/385151591524597761/1118427954377146378"
label = "Discord"
position = "right"

[navbar.logo]
src = "/favicon.ico"

[footer]
style = "dark"
copyright = "Copyright Â© 2025 SolarScuffle-Bot. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"
